## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

notifications:
  email: false

os:
  - linux
  - freebsd
  - osx
  - windows
julia:
  - 1.3
  - 1
  - nightly

branches:
  only:
  - master
  - gh-pages # For building documentation
  - /^testing-.*$/ # testing branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

cache:
  directories:
  - $HOME/.julia/artifacts

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate();
                                               Pkg.build("FINUFFT")'
        - julia --project=docs/ docs/make.jl
      after_success: skip

coveralls: true
